import{a as l,S as m,i as f}from"./assets/vendor-CYg6pwNI.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const h="49237472-e2704486942ee192f1a430e77",g="https://pixabay.com/api/";l({method:"get",url:"https://jsonplaceholder.typicode.com/users"});async function y(o){try{return(await l.get(g,{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(t){return console.error("Error fetching images:",t),[]}}const c=document.querySelector(".gallery"),i=document.querySelector(".loader");let L=new m(".gallery a");function w(o){if(c.innerHTML="",o.length===0){p("Sorry, there are no images matching your search query. Please try again!");return}const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:u,downloads:d})=>`
            <li>
                <a href="${a}">
                    <img src="${s}" alt="${e}" loading="lazy">
                </a>
                <div><p>Likes: <span>${r}</span></p> <p> Views: <span>${n}</span></p> <p> Comments: <span>${u}</span></p> <p> Downloads: <span>${d}</span></p></div>
            </li>
        `).join("");c.innerHTML=t,L.refresh()}function E(){i.classList.remove("hidden"),i.innerHTML='<p class="loader-text">Loading images, please wait...</p>'}function v(){i.classList.add("hidden")}function p(o){f.error({title:"Error",message:o,position:"topRight"})}const b=document.getElementById("search-form"),P=document.getElementById("search-input");b.addEventListener("submit",async o=>{o.preventDefault();const t=P.value.trim();if(!t){p("Please enter a search term!");return}E();const s=await y(t);v(),w(s)});
//# sourceMappingURL=index.js.map
