import{a as c,S as f,i as m}from"./assets/vendor-CYg6pwNI.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const h="49237472-e2704486942ee192f1a430e77",y="https://pixabay.com/api/";c({method:"get",url:"https://jsonplaceholder.typicode.com/users"});async function g(o){try{return(await c.get(y,{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(t){return console.error("Error fetching images:",t),[]}}const a=document.querySelector(".gallery"),l=document.querySelector(".loader");let L=new f(".gallery a");function E(o){if(a.innerHTML="",o.length===0){u("Sorry, there are no images matching your search query. Please try again!");return}const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:p,downloads:d})=>`
            <li>
                <a href="${i}">
                    <img src="${s}" alt="${e}" loading="lazy">
                </a>
                <div><p>Likes: <span>${r}</span></p> <p> Views: <span>${n}</span></p> <p> Comments: <span>${p}</span></p> <p> Downloads: <span>${d}</span></p></div>
            </li>
        `).join("");a.innerHTML=t,L.refresh()}function v(){l.classList.remove("hidden")}function w(){l.classList.add("hidden")}function u(o){m.error({title:"Error",message:o,position:"topRight"})}const b=document.getElementById("search-form"),P=document.getElementById("search-input");b.addEventListener("submit",async o=>{o.preventDefault();const t=P.value.trim();if(!t){u("Please enter a search term!");return}v();const s=await g(t);w(),E(s)});
//# sourceMappingURL=index.js.map
